#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelTakip
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	using System.Runtime.Remoting.Messaging;

	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbo_PersonelTakip")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAYLAR(AYLAR instance);
    partial void UpdateAYLAR(AYLAR instance);
    partial void DeleteAYLAR(AYLAR instance);
    partial void InsertDepartmanClass(DepartmanClass instance);
    partial void UpdateDepartmanClass(DepartmanClass instance);
    partial void DeleteDepartmanClass(DepartmanClass instance);
    partial void InsertIzinClass(IzinClass instance);
    partial void UpdateIzinClass(IzinClass instance);
    partial void DeleteIzinClass(IzinClass instance);
    partial void InsertIzinDurum(IzinDurum instance);
    partial void UpdateIzinDurum(IzinDurum instance);
    partial void DeleteIzinDurum(IzinDurum instance);
    partial void Insertİs(İs instance);
    partial void Updateİs(İs instance);
    partial void Deleteİs(İs instance);
    partial void InsertİsDurum(İsDurum instance);
    partial void UpdateİsDurum(İsDurum instance);
    partial void DeleteİsDurum(İsDurum instance);
    partial void InsertMaasClass(MaasClass instance);
    partial void UpdateMaasClass(MaasClass instance);
    partial void DeleteMaasClass(MaasClass instance);
    partial void InsertPersonelClass(PersonelClass instance);
    partial void UpdatePersonelClass(PersonelClass instance);
    partial void DeletePersonelClass(PersonelClass instance);
    partial void InsertPozisyonClass(PozisyonClass instance);
    partial void UpdatePozisyonClass(PozisyonClass instance);
    partial void DeletePozisyonClass(PozisyonClass instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PersonelTakip.Properties.Settings.Default.dbo_PersonelTakipConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AYLAR> AYLAR
		{
			get
			{
				return this.GetTable<AYLAR>();
			}
		}
		
		public System.Data.Linq.Table<DepartmanClass> DepartmanClass
		{
			get
			{
				return this.GetTable<DepartmanClass>();
			}
		}
		
		public System.Data.Linq.Table<IzinClass> IzinClass
		{
			get
			{
				return this.GetTable<IzinClass>();
			}
		}
		
		public System.Data.Linq.Table<IzinDurum> IzinDurum
		{
			get
			{
				return this.GetTable<IzinDurum>();
			}
		}
		
		public System.Data.Linq.Table<İs> İs
		{
			get
			{
				return this.GetTable<İs>();
			}
		}
		
		public System.Data.Linq.Table<İsDurum> İsDurum
		{
			get
			{
				return this.GetTable<İsDurum>();
			}
		}
		
		public System.Data.Linq.Table<MaasClass> MaasClass
		{
			get
			{
				return this.GetTable<MaasClass>();
			}
		}
		
		public System.Data.Linq.Table<PersonelClass> PersonelClass
		{
			get
			{
				return this.GetTable<PersonelClass>();
			}
		}
		
		public System.Data.Linq.Table<PozisyonClass> PozisyonClass
		{
			get
			{
				return this.GetTable<PozisyonClass>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AYLAR")]
	public partial class AYLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAyChanging(string value);
    partial void OnAyChanged();
    #endregion
		
		public AYLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ay", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Ay
		{
			get
			{
				return this._Ay;
			}
			set
			{
				if ((this._Ay != value))
				{
					this.OnAyChanging(value);
					this.SendPropertyChanging();
					this._Ay = value;
					this.SendPropertyChanged("Ay");
					this.OnAyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DepartmanClass")]
	public partial class DepartmanClass : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DepartmanAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDepartmanAdChanging(string value);
    partial void OnDepartmanAdChanged();
    #endregion
		
		public DepartmanClass()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanAd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DepartmanAd
		{
			get
			{
				return this._DepartmanAd;
			}
			set
			{
				if ((this._DepartmanAd != value))
				{
					this.OnDepartmanAdChanging(value);
					this.SendPropertyChanging();
					this._DepartmanAd = value;
					this.SendPropertyChanged("DepartmanAd");
					this.OnDepartmanAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IzinClass")]
	public partial class IzinClass : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _PersonelID;
		
		private System.DateTime _IzinBaslamaTarih;
		
		private System.DateTime _IzinBitisTarih;
		
		private string _Aciklama;
		
		private int _Sure;
		
		private int _IzinDurumID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPersonelIDChanging(int value);
    partial void OnPersonelIDChanged();
    partial void OnIzinBaslamaTarihChanging(System.DateTime value);
    partial void OnIzinBaslamaTarihChanged();
    partial void OnIzinBitisTarihChanging(System.DateTime value);
    partial void OnIzinBitisTarihChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSureChanging(int value);
    partial void OnSureChanged();
    partial void OnIzinDurumIDChanging(int value);
    partial void OnIzinDurumIDChanged();
    #endregion
		
		public IzinClass()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", DbType="Int NOT NULL")]
		public int PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinBaslamaTarih", DbType="Date NOT NULL")]
		public System.DateTime IzinBaslamaTarih
		{
			get
			{
				return this._IzinBaslamaTarih;
			}
			set
			{
				if ((this._IzinBaslamaTarih != value))
				{
					this.OnIzinBaslamaTarihChanging(value);
					this.SendPropertyChanging();
					this._IzinBaslamaTarih = value;
					this.SendPropertyChanged("IzinBaslamaTarih");
					this.OnIzinBaslamaTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinBitisTarih", DbType="Date NOT NULL")]
		public System.DateTime IzinBitisTarih
		{
			get
			{
				return this._IzinBitisTarih;
			}
			set
			{
				if ((this._IzinBitisTarih != value))
				{
					this.OnIzinBitisTarihChanging(value);
					this.SendPropertyChanging();
					this._IzinBitisTarih = value;
					this.SendPropertyChanged("IzinBitisTarih");
					this.OnIzinBitisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int NOT NULL")]
		public int Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinDurumID", DbType="Int NOT NULL")]
		public int IzinDurumID
		{
			get
			{
				return this._IzinDurumID;
			}
			set
			{
				if ((this._IzinDurumID != value))
				{
					this.OnIzinDurumIDChanging(value);
					this.SendPropertyChanging();
					this._IzinDurumID = value;
					this.SendPropertyChanged("IzinDurumID");
					this.OnIzinDurumIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IzinDurum")]
	public partial class IzinDurum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _IzinDurumAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIzinDurumAdChanging(string value);
    partial void OnIzinDurumAdChanged();
    #endregion
		
		public IzinDurum()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinDurumAd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IzinDurumAd
		{
			get
			{
				return this._IzinDurumAd;
			}
			set
			{
				if ((this._IzinDurumAd != value))
				{
					this.OnIzinDurumAdChanging(value);
					this.SendPropertyChanging();
					this._IzinDurumAd = value;
					this.SendPropertyChanged("IzinDurumAd");
					this.OnIzinDurumAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.İs")]
	public partial class İs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _PersonelID;
		
		private string _Baslik;
		
		private string _Icerik;
		
		private System.DateTime _IsBaslamaTarih;
		
		private System.DateTime _IsBitisTarih;
		
		private int _IsDurumID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPersonelIDChanging(int value);
    partial void OnPersonelIDChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnIcerikChanging(string value);
    partial void OnIcerikChanged();
    partial void OnIsBaslamaTarihChanging(System.DateTime value);
    partial void OnIsBaslamaTarihChanged();
    partial void OnIsBitisTarihChanging(System.DateTime value);
    partial void OnIsBitisTarihChanged();
    partial void OnIsDurumIDChanging(int value);
    partial void OnIsDurumIDChanged();
    #endregion
		
		public İs()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", DbType="Int NOT NULL")]
		public int PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Baslik
		{
			get
			{
				return this._Baslik;
			}
			set
			{
				if ((this._Baslik != value))
				{
					this.OnBaslikChanging(value);
					this.SendPropertyChanging();
					this._Baslik = value;
					this.SendPropertyChanged("Baslik");
					this.OnBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icerik", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Icerik
		{
			get
			{
				return this._Icerik;
			}
			set
			{
				if ((this._Icerik != value))
				{
					this.OnIcerikChanging(value);
					this.SendPropertyChanging();
					this._Icerik = value;
					this.SendPropertyChanged("Icerik");
					this.OnIcerikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBaslamaTarih", DbType="Date NOT NULL")]
		public System.DateTime IsBaslamaTarih
		{
			get
			{
				return this._IsBaslamaTarih;
			}
			set
			{
				if ((this._IsBaslamaTarih != value))
				{
					this.OnIsBaslamaTarihChanging(value);
					this.SendPropertyChanging();
					this._IsBaslamaTarih = value;
					this.SendPropertyChanged("IsBaslamaTarih");
					this.OnIsBaslamaTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBitisTarih", DbType="Date NOT NULL")]
		public System.DateTime IsBitisTarih
		{
			get
			{
				return this._IsBitisTarih;
			}
			set
			{
				if ((this._IsBitisTarih != value))
				{
					this.OnIsBitisTarihChanging(value);
					this.SendPropertyChanging();
					this._IsBitisTarih = value;
					this.SendPropertyChanged("IsBitisTarih");
					this.OnIsBitisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDurumID", DbType="Int NOT NULL")]
		public int IsDurumID
		{
			get
			{
				return this._IsDurumID;
			}
			set
			{
				if ((this._IsDurumID != value))
				{
					this.OnIsDurumIDChanging(value);
					this.SendPropertyChanging();
					this._IsDurumID = value;
					this.SendPropertyChanged("IsDurumID");
					this.OnIsDurumIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.İsDurum")]
	public partial class İsDurum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _IsDurumAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIsDurumAdChanging(string value);
    partial void OnIsDurumAdChanged();
    #endregion
		
		public İsDurum()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDurumAd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IsDurumAd
		{
			get
			{
				return this._IsDurumAd;
			}
			set
			{
				if ((this._IsDurumAd != value))
				{
					this.OnIsDurumAdChanging(value);
					this.SendPropertyChanging();
					this._IsDurumAd = value;
					this.SendPropertyChanged("IsDurumAd");
					this.OnIsDurumAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MaasClass")]
	public partial class MaasClass : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _PersonelID;
		
		private int _Miktar;
		
		private int _YIL;
		
		private int _AyID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPersonelIDChanging(int value);
    partial void OnPersonelIDChanged();
    partial void OnMiktarChanging(int value);
    partial void OnMiktarChanged();
    partial void OnYILChanging(int value);
    partial void OnYILChanged();
    partial void OnAyIDChanging(int value);
    partial void OnAyIDChanged();
    #endregion
		
		public MaasClass()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", DbType="Int NOT NULL")]
		public int PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miktar", DbType="Int NOT NULL")]
		public int Miktar
		{
			get
			{
				return this._Miktar;
			}
			set
			{
				if ((this._Miktar != value))
				{
					this.OnMiktarChanging(value);
					this.SendPropertyChanging();
					this._Miktar = value;
					this.SendPropertyChanged("Miktar");
					this.OnMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YIL", DbType="Int NOT NULL")]
		public int YIL
		{
			get
			{
				return this._YIL;
			}
			set
			{
				if ((this._YIL != value))
				{
					this.OnYILChanging(value);
					this.SendPropertyChanging();
					this._YIL = value;
					this.SendPropertyChanged("YIL");
					this.OnYILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AyID", DbType="Int NOT NULL")]
		public int AyID
		{
			get
			{
				return this._AyID;
			}
			set
			{
				if ((this._AyID != value))
				{
					this.OnAyIDChanging(value);
					this.SendPropertyChanging();
					this._AyID = value;
					this.SendPropertyChanged("AyID");
					this.OnAyIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonelClass")]
	public partial class PersonelClass : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _UserNo;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Resim;
		
		private int _DepartmanID;
		
		private int _PozisyonID;
		
		private int _Maas;
		
		private System.Nullable<System.DateTime> _DogumGunu;
		
		private string _Adres;
		
		private string _Password;
		
		private bool _isAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserNoChanging(int value);
    partial void OnUserNoChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnResimChanging(string value);
    partial void OnResimChanged();
    partial void OnDepartmanIDChanging(int value);
    partial void OnDepartmanIDChanged();
    partial void OnPozisyonIDChanging(int value);
    partial void OnPozisyonIDChanged();
    partial void OnMaasChanging(int value);
    partial void OnMaasChanged();
    partial void OnDogumGunuChanging(System.Nullable<System.DateTime> value);
    partial void OnDogumGunuChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnisAdminChanging(bool value);
    partial void OnisAdminChanged();
    #endregion
		
		public PersonelClass()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="Int NOT NULL")]
		public int UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					this.OnUserNoChanging(value);
					this.SendPropertyChanging();
					this._UserNo = value;
					this.SendPropertyChanged("UserNo");
					this.OnUserNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanID", DbType="Int NOT NULL")]
		public int DepartmanID
		{
			get
			{
				return this._DepartmanID;
			}
			set
			{
				if ((this._DepartmanID != value))
				{
					this.OnDepartmanIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmanID = value;
					this.SendPropertyChanged("DepartmanID");
					this.OnDepartmanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PozisyonID", DbType="Int NOT NULL")]
		public int PozisyonID
		{
			get
			{
				return this._PozisyonID;
			}
			set
			{
				if ((this._PozisyonID != value))
				{
					this.OnPozisyonIDChanging(value);
					this.SendPropertyChanging();
					this._PozisyonID = value;
					this.SendPropertyChanged("PozisyonID");
					this.OnPozisyonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maas", DbType="Int NOT NULL")]
		public int Maas
		{
			get
			{
				return this._Maas;
			}
			set
			{
				if ((this._Maas != value))
				{
					this.OnMaasChanging(value);
					this.SendPropertyChanging();
					this._Maas = value;
					this.SendPropertyChanged("Maas");
					this.OnMaasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumGunu", DbType="Date")]
		public System.Nullable<System.DateTime> DogumGunu
		{
			get
			{
				return this._DogumGunu;
			}
			set
			{
				if ((this._DogumGunu != value))
				{
					this.OnDogumGunuChanging(value);
					this.SendPropertyChanging();
					this._DogumGunu = value;
					this.SendPropertyChanged("DogumGunu");
					this.OnDogumGunuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(MAX)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAdmin", DbType="Bit NOT NULL")]
		public bool isAdmin
		{
			get
			{
				return this._isAdmin;
			}
			set
			{
				if ((this._isAdmin != value))
				{
					this.OnisAdminChanging(value);
					this.SendPropertyChanging();
					this._isAdmin = value;
					this.SendPropertyChanged("isAdmin");
					this.OnisAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

   //     internal static bool isUnique(int v)
   //     {
			//List<Personel> list = new List<Personel>(v);

   //        if(list.Count > 0)
			//{
			//	return true;
			//}



			//	return false;
   //     }

    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PozisyonClass")]
	public partial class PozisyonClass : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PozisyonAdı;
		
		private int _DepartmanID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPozisyonAdıChanging(string value);
    partial void OnPozisyonAdıChanged();
    partial void OnDepartmanIDChanging(int value);
    partial void OnDepartmanIDChanged();
    #endregion
		
		public PozisyonClass()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PozisyonAdı", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PozisyonAdı
		{
			get
			{
				return this._PozisyonAdı;
			}
			set
			{
				if ((this._PozisyonAdı != value))
				{
					this.OnPozisyonAdıChanging(value);
					this.SendPropertyChanging();
					this._PozisyonAdı = value;
					this.SendPropertyChanged("PozisyonAdı");
					this.OnPozisyonAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanID", DbType="Int NOT NULL")]
		public int DepartmanID
		{
			get
			{
				return this._DepartmanID;
			}
			set
			{
				if ((this._DepartmanID != value))
				{
					this.OnDepartmanIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmanID = value;
					this.SendPropertyChanged("DepartmanID");
					this.OnDepartmanIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
